# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Meet\Desktop\UI Converter\Book.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(349, 242)
        self.verticalLayout = QtWidgets.QVBoxLayout(form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.t1 = QtWidgets.QLineEdit(form)
        self.t1.setObjectName("t1")
        self.horizontalLayout.addWidget(self.t1)
        self.pushButton = QtWidgets.QPushButton(form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.t3 = QtWidgets.QLineEdit(form)
        self.t3.setText("")
        self.t3.setObjectName("t3")
        self.horizontalLayout_4.addWidget(self.t3)
        spacerItem = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.t2 = QtWidgets.QLineEdit(form)
        self.t2.setObjectName("t2")
        self.horizontalLayout_2.addWidget(self.t2)
        self.pushButton_2 = QtWidgets.QPushButton(form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.t4 = QtWidgets.QLineEdit(form)
        self.t4.setText("")
        self.t4.setObjectName("t4")
        self.horizontalLayout_3.addWidget(self.t4)
        spacerItem2 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

        self.pushButton.pressed.connect(self.Get_Price)
        self.pushButton_2.pressed.connect(self.Total)

        self.cost = 0

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Book Manager"))
        self.label.setText(_translate("form", "Book Title"))
        self.pushButton.setText(_translate("form", "Get Price"))
        self.label_2.setText(_translate("form", "Price (Rs.)"))
        self.label_3.setText(_translate("form", "Quantity "))
        self.pushButton_2.setText(_translate("form", "Total"))
        self.label_4.setText(_translate("form", "Total (Rs.)"))

    def Get_Price(self):
        import sqlite3
        MyBook = sqlite3.connect('bookdatabase.db')
        cursbook = MyBook.cursor()
        name = str(self.t1.text())
        query = '''SELECT * from Books where Name = '%s' ''' % (name,)
        cursbook.execute(query)
        data = cursbook.fetchall()
        book_tuple = data[0]
        name_book = book_tuple[0]
        price_book = book_tuple[2]
        if name == name_book:
            self.t2.setText(str(price_book))
            self.cost = int(price_book)
        else:
            return 'Book not found'

    def Total(self):
        num = (self.t3.text())
        if num:
            num = int(num)
            self.t4.setText(str(self.cost * num))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    ui = Ui_form()
    ui.setupUi(form)
    form.show()
    sys.exit(app.exec_())
