# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Meet\Desktop\UI Converter\Evaluate.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_evaluate(object):
    def setupUi(self, evaluate):
        evaluate.setObjectName("evaluate")
        evaluate.resize(501, 415)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "C:\\Users\\Meet\\Desktop\\UI Converter\\../../PycharmProjects/untitled/Internshala/Final Project/calculate.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        evaluate.setWindowIcon(icon)
        evaluate.setWindowOpacity(1.0)

        self.verticalLayout = QtWidgets.QVBoxLayout(evaluate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(evaluate)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(evaluate)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.Team = QtWidgets.QComboBox(evaluate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Team.sizePolicy().hasHeightForWidth())
        self.Team.setSizePolicy(sizePolicy)
        self.Team.setMinimumSize(QtCore.QSize(141, 22))
        self.Team.setEditable(False)
        self.Team.setCurrentText("")
        self.Team.setObjectName("Team")

        import sqlite3
        myteam = sqlite3.connect('final.db')
        query = "SELECT Name FROM teams"
        cursteam = myteam.cursor()
        data = cursteam.execute(query)
        teams = []
        for row in data:
            self.Team.addItem(row[0])
        myteam.close()

        self.horizontalLayout_5.addWidget(self.Team)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(61, 23, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(evaluate)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.Match = QtWidgets.QComboBox(evaluate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Match.sizePolicy().hasHeightForWidth())
        self.Match.setSizePolicy(sizePolicy)
        self.Match.setMinimumSize(QtCore.QSize(141, 22))
        self.Match.setEditable(False)
        self.Match.setCurrentText("")
        self.Match.setObjectName("Match")
        self.Match.addItem("")
        self.Match.addItem("")
        self.Match.addItem("")
        self.horizontalLayout_5.addWidget(self.Match)
        spacerItem2 = QtWidgets.QSpacerItem(61, 23, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(evaluate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.Players = QtWidgets.QLabel(evaluate)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Players.setFont(font)
        self.Players.setObjectName("Players")
        self.horizontalLayout_6.addWidget(self.Players)
        spacerItem4 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.Points = QtWidgets.QLabel(evaluate)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Points.setFont(font)
        self.Points.setObjectName("Points")
        self.horizontalLayout_6.addWidget(self.Points)
        spacerItem5 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.player_list = QtWidgets.QListWidget(evaluate)
        self.player_list.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.player_list.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.player_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.player_list.setObjectName("player_list")
        self.horizontalLayout_7.addWidget(self.player_list)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.line_2 = QtWidgets.QFrame(evaluate)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        spacerItem9 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.points_list = QtWidgets.QListWidget(evaluate)
        self.points_list.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.points_list.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.points_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.points_list.setObjectName("points_list")
        self.horizontalLayout_7.addWidget(self.points_list)
        spacerItem10 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem12 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.label_3 = QtWidgets.QLabel(evaluate)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.Calculate_score = QtWidgets.QPushButton(evaluate)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Calculate_score.setFont(font)
        self.Calculate_score.setMouseTracking(False)
        self.Calculate_score.setObjectName("Calculate_score")

        self.Calculate_score.clicked.connect(self.calculate)

        self.horizontalLayout_10.addWidget(self.Calculate_score)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem16)
        spacerItem17 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.lineEdit = QtWidgets.QLineEdit(evaluate)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_10.addWidget(self.lineEdit)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem18)
        spacerItem19 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem19)
        self.verticalLayout.addLayout(self.horizontalLayout_10)

        self.retranslateUi(evaluate)
        QtCore.QMetaObject.connectSlotsByName(evaluate)

    def calculate(self):
        import sqlite3
        myplayers = sqlite3.connect('final.db')
        team = self.Team.currentText()
        self.player_list.clear()
        query = '''SELECT Players, Value FROM teams WHERE Name = '%s' ''' % (team,)
        cursplayers = myplayers.cursor()
        data = cursplayers.execute(query)
        row1 = data.fetchone()
        # print (row[0])
        selected = row1[0].split(',')
        # print (selected)
        self.player_list.addItems(selected)
        team_score = 0
        self.points_list.clear()
        match = self.Match.currentText()
        for i in range(self.player_list.count()):
            total = 0
            batscore = 0
            bowlscore = 0
            fieldscore = 0
            name = self.player_list.item(i).text()
            query1 = '''SELECT * FROM '%s' WHERE Player= '%s' ''' % (match, name)
            curscore = myplayers.cursor()
            data1 = curscore.execute(query1)
            row = data1.fetchone()
            # print (row)

            batscore = int(row[1] / 2)
            if row[1] >= 50:
                batscore += 5
            if row[1] >= 100:
                batscore += 10
            if row[1] > 0:
                strike_rate = (row[1] / row[2]) * 100
                if 80 <= strike_rate <= 100:
                    batscore += 2
                if strike_rate > 100:
                    batscore += 4
                if row[3] != 0:
                    batscore += int(row[3])
                if row[4] != 0:
                    batscore += (2 * (int(row[4])))
            # print ("batting score=", batscore)

            bowlscore = row[8] * 10
            if row[8] >= 3:
                bowlscore += 5
            if row[8] >= 5:
                bowlscore += 10
            if row[7] > 0:
                economy_rate = row[7] / (row[5] / 6)
                if 3.5 < economy_rate < 4.5:
                    bowlscore += 4
                if 2 < economy_rate < 3.5:
                    bowlscore += 7
                if economy_rate < 2:
                    bowlscore += 10
            fieldscore = (row[9] + row[10] + row[11]) * 10
            total = batscore + bowlscore + fieldscore
            self.points_list.addItem(str(total))
            team_score = team_score + total
        self.lineEdit.setText(str(team_score))

    def retranslateUi(self, evaluate):
        _translate = QtCore.QCoreApplication.translate
        evaluate.setWindowTitle(_translate("evaluate", "Evaluate Score"))
        self.label_4.setText(_translate("evaluate", "    "))
        self.label.setText(_translate("evaluate", "Teams"))
        self.label_2.setText(_translate("evaluate", "Matches"))
        self.Match.setItemText(0, _translate("Dialog", "match"))
        self.Match.setItemText(1, _translate("Dialog", "Match1"))
        self.Match.setItemText(2, _translate("Dialog", "Match2"))
        self.Players.setText(_translate("evaluate", "                  Players ↓ "))
        self.Points.setText(_translate("evaluate", "                   Points ↓ "))
        self.Calculate_score.setText(_translate("evaluate", "Calculate Store"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    evaluate = QtWidgets.QWidget()
    ui = Ui_evaluate()
    ui.setupUi(evaluate)
    evaluate.show()
    sys.exit(app.exec_())
